### PR TITLE
Break time is over 😅 Onto the final sprint

### PR DESCRIPTION
**Pull request by kbinhnguyen**
Features in this PR:
- [X] Account management both front and backend (frontend error handling not complete though):
  - [X] Password recovery if forgotten
  - [X] Resend email verification link if did not receive
  - [X] Change email
  - [X] Change password
  - [X] Change username
- [X] Implement a notification queue in the db for existing functionalities (still need to write query to retrieve these notifications, and mutation to delete them from client side + respective resolver functions)
- [X] User can now log in using either email or username
- [X] Webhook event of paid invoice will write to `invoices` table in db (still need to write query & resolver to retrieve these from client side)

### CODE REVIEW

**Review by codingavatar — APPROVED** [review]
Looks really great! Thanks for reorganizing our files, too!

**Comment by kbinhnguyen** [comment]
[Notification queue in db](https://trello.com/c/lCw0TSTJ/51-notification-queue-in-db)

**Comment by kbinhnguyen** [comment]
[Change email / username / password; forgot username/ password](https://trello.com/c/cHoIRhJh/6-change-email-username-password-forgot-username-password)

**Comment by kbinhnguyen** [comment]
[Resend verify email](https://trello.com/c/H046nnit/46-resend-verify-email)

**Comment by kbinhnguyen** [comment]
[Log in using either username or email](https://trello.com/c/YpkBQe6a/53-log-in-using-either-username-or-email)

**Pull request merged**
